// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleTransformer.AppDb;

#nullable disable

namespace SimpleTransformer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925102200_AddSourceFileNamesToTrainingJobs")]
    partial class AddSourceFileNamesToTrainingJobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("SimpleTransformer.AppDb.TrainingCheckpointEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Epoch")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Loss")
                        .HasColumnType("REAL");

                    b.Property<string>("Sha256")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TrainingRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransformerModelId")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("TransformerModelId");

                    b.HasIndex("Filepath", "Filename")
                        .IsUnique();

                    b.ToTable("TrainingCheckpoints");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TrainingConfigEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.ToTable("TrainingConfigs");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TrainingConfigPresetEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrainingConfigEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TrainingConfigPresets");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TrainingJobEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BatchesCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CheckpointFilename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentBatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentEpoch")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CurrentLoss")
                        .HasColumnType("REAL");

                    b.Property<int>("CurrentSubBatch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateStarted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpochsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PreviousCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubBatchesCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalBatches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalEpochs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSubBatches")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TrainingCheckpointId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrainingConfigId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransformerConfigId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransformerModelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VocabularyId")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TrainingCheckpointId");

                    b.HasIndex("TrainingConfigId");

                    b.HasIndex("TransformerConfigId");

                    b.HasIndex("TransformerModelId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("TrainingJobs");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TransformerConfigEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.ToTable("TransformerConfigs");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TransformerConfigPresetEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransformerConfigId")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TransformerConfigPresets");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TransformerModelEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccelerationBackend")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLoaded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrainingConfigId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TransformerConfigId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseQLora")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TrainingConfigId");

                    b.HasIndex("TransformerConfigId");

                    b.ToTable("TransformerModels");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.VocabularyEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filepath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TokenizerType")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntryId");

                    b.ToTable("Vocabularies");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TrainingCheckpointEntry", b =>
                {
                    b.HasOne("SimpleTransformer.AppDb.TransformerModelEntry", "TransformerModel")
                        .WithMany()
                        .HasForeignKey("TransformerModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TransformerModel");
                });

            modelBuilder.Entity("SimpleTransformer.AppDb.TrainingJobEntry", b =>
                {
                    b.HasOne("SimpleTransformer.AppDb.TrainingCheckpointEntry", "TrainingCheckpoint")
                        .WithMany()
                        .HasForeignKey("TrainingCheckpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SimpleTransformer.AppDb.TrainingConfigEntry", "TrainingConfig")
                        .WithMany()
                        .HasForeignKey("TrainingConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleTransformer.AppDb.TransformerConfigEntry", "TransformerConfig")
                        .WithMany()
                        .HasForeignKey("TransformerConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleTransformer.AppDb.TransformerModelEntry", "TransformerModel")
                        .WithMany()
                        .HasForeignKey("TransformerModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleTransformer.AppDb.VocabularyEntry", "Vocabulary")
                        .WithMany()
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingCheckpoint");

                    b.Navigation("TrainingConfig");

                    b.Navigation("TransformerConfig");

                    b.Navigation("TransformerModel");

                    b.Navigation("Vocabulary");
                });
#pragma warning restore 612, 618
        }
    }
}
